quarkus.application.name=country-query-service
quarkus.rest-client.country-service.url=https://restcountries.com/v3.1
quarkus.rest-client.country-service.connect-timeout=20000
quarkus.rest-client.country-service.read-timeout=20000

quarkus.datasource.db-kind=postgresql
%prod.quarkus.datasource.reactive.url=${COUNTRY_DB_URL:vertx-reactive:postgresql://localhost:5432/countrydb}
quarkus.datasource.username=${COUNTRY_DB_USERNAME:user}
quarkus.datasource.password=${COUNTRY_DB_PASSWORD:pass}
quarkus.hibernate-orm.database.generation=drop-and-create

# Generate Java from the WSDL
quarkus.cxf.codegen.wsdl2java.includes=wsdl/CountryInfoService.wsdl
quarkus.cxf.codegen.wsdl2java.additional-params=-b,src/main/resources/wsdl/async-binding.xml,-wsdlLocation,classpath:wsdl/CountryInfoService.wsdl


# SOAP client configuration
quarkus.cxf.client."country-info".service-interface=org.oorsprong.websamples_countryinfo.CountryInfoServiceSoapType
quarkus.cxf.client."country-info".client-endpoint-url=http://webservices.oorsprong.org/websamples.countryinfo/CountryInfoService.wso

# SOAP endpoint configuration
quarkus.cxf.endpoint./soap/countries.implementor=com.countryqueryservice.soap.CountrySoapEndpoint
quarkus.cxf.endpoint./soap/countries.service-name={http://countryqueryservice.com/soap/v1}CountrySoapService
quarkus.cxf.endpoint./soap/countries.port-name={http://countryqueryservice.com/soap/v1}CountrySoapPort
