quarkus.application.name=country-query-service
quarkus.rest-client.country-service.url=https://restcountries.com/v3.1
quarkus.rest-client.country-service.connect-timeout=20000
quarkus.rest-client.country-service.read-timeout=20000

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=user
quarkus.datasource.password=pass
quarkus.hibernate-orm.database.generation=drop-and-create

# Generate Java from the WSDL
quarkus.cxf.codegen.wsdl2java.includes=wsdl/CountryInfoService.wsdl

# SOAP client configuration
quarkus.cxf.client."country-info".service-interface=org.oorsprong.websamples_countryinfo.CountryInfoServiceSoapType
quarkus.cxf.client."country-info".client-endpoint-url=http://webservices.oorsprong.org/websamples.countryinfo/CountryInfoService.wso

# SOAP endpoint configuration
quarkus.cxf.endpoint./soap/countries.implementor=com.countryqueryservice.soap.CountrySoapEndpoint
quarkus.cxf.endpoint./soap/countries.service-name={http://countryqueryservice.com/soap/v1}CountrySoapService
quarkus.cxf.endpoint./soap/countries.port-name={http://countryqueryservice.com/soap/v1}CountrySoapPort
