quarkus.application.name=country-query-service
quarkus.rest-client.country-service.url=https://restcountries.com/v3.1
quarkus.rest-client.country-service.connect-timeout=20000
quarkus.rest-client.country-service.read-timeout=20000

quarkus.datasource.db-kind=postgresql
%prod.quarkus.datasource.reactive.url=${COUNTRY_DB_URL:vertx-reactive:postgresql://localhost:5432/countrydb}
quarkus.datasource.username=${COUNTRY_DB_USERNAME:user}
quarkus.datasource.password=${COUNTRY_DB_PASSWORD:pass}
quarkus.hibernate-orm.database.generation=drop-and-create
